image: Visual Studio 2019

before_build:
    - nuget restore SecondSemester\Homework7\Clock.sln

build:
    project: SecondSemester\Homework7\Clock.sln

test_script:
    - dotnet test SecondSemester\Homework7\Clock.sln